CREATE TABLE `central_city_dev` (
  `OGR_FID` int(11) NOT NULL AUTO_INCREMENT,
  `SHAPE` geometry NOT NULL,
  `projectid` double DEFAULT NULL,
  `propid` text,
  `stateid` text,
  `buildingid` text,
  `lurs` text,
  `developmentname` text,
  `address` text,
  `zip` double DEFAULT NULL,
  `status` text,
  `subdist` text,
  `designapprvl` double DEFAULT NULL,
  `yrbuiltrehab` double DEFAULT NULL,
  `bldgsf` double DEFAULT NULL,
  `sitesf` double DEFAULT NULL,
  `resunits` double DEFAULT NULL,
  `ressf` double DEFAULT NULL,
  `retailsf` double DEFAULT NULL,
  `officeindsf` double DEFAULT NULL,
  `hotelrooms` double DEFAULT NULL,
  `baseht` double DEFAULT NULL,
  `finalht` double DEFAULT NULL,
  `basezone` text,
  `generalizedzone` text,
  `basefar` double DEFAULT NULL,
  `finalfar` double DEFAULT NULL,
  `farpertgused` double DEFAULT NULL,
  `parkspcs` double DEFAULT NULL,
  `parkingtype` text,
  `heightbonus` text,
  `farbonuses` text,
  `fartransfers` text,
  `notes` text,
  `map_source` text,
  `display_date` datetime DEFAULT NULL,
  `date_valid` text,
  `percent_far` double DEFAULT NULL,
  `latitude` double DEFAULT NULL,
  `longitude` double DEFAULT NULL,
  UNIQUE KEY `OGR_FID` (`OGR_FID`),
  SPATIAL KEY `SHAPE` (`SHAPE`)
) ENGINE=MyISAM AUTO_INCREMENT=302 DEFAULT CHARSET=utf8;
